name: Gen

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  act:
    name: Generate stats using act
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.WRITE_TOKEN }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Run act
        run: |
          docker run --rm
           -it
           -v "${PWD}":/workdir \
           ghcr.io/kijimad/act:latest
